name: Python application
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read
  pull-requests: write

jobs:
   build:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         python3 -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: run main
       env:
         MICRO_PASS: ${{ secrets.MICRO_PASS }}
         TOKENID: ${{ secrets.TOKENID }}
         IDINSTANCE: ${{ secrets.IDINSTANCE }}
       run: |
         python3 main.py

     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: master