name: Python application
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 2 * * *"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: read
  pull-requests: write

jobs:
   build:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         python3 -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: run main
       env:
         MICRO_PASS: ${{ secrets.MICRO_PASS }}
         TOKENID: ${{ secrets.TOKENID }}
         IDINSTANCE: ${{ secrets.IDINSTANCE }}
       run: |
         python3 main.py

     - name: Commit report
       run: |
           git config --global user.name 'Akmal Hameed'
           git config --global user.email 'sakmalh@users.noreply.github.com'
           git commit -am "Added Logs"
           git push