name: Python application
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write
jobs:
   build:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         python3 -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: run main
       env:
         MICRO_PASS: ${{ secrets.MICRO_PASS }}
       run: |
         python3 main.py
     - name: Upload image as artifact
       uses: actions/upload-artifact@v2
       with:
         name: generated-image
         path: test.png
