# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Set up WireGuard
       env:
         IPS: ${{ secrets.IPS }}
         PRIVATE: ${{ secrets.PRIVATE }}
         PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
         PRESHARED: ${{ secrets.PRESHARED }}
         ENDPOINT: ${{ secrets.ENDPOINT }}
       run:
         python wireguard.py
         sudo apt-get update && sudo apt-get upgrade -y
         sudo apt-get install wireguard
         sudo cp /path/to/wireguard.conf /etc/wireguard/wg0.conf
         yes | cp -rf wireguard.conf /etc/wireguard/wg0.conf
         sudo wg-quick up wg0

     - name: Check IP
       run: curl ifconfig.me
     - name: run main
       env:
         MICRO_PASS: ${{ secrets.MICRO_PASS }}
       run: |
         python main.py
     - name: Upload image as artifact
       uses: actions/upload-artifact@v2
       with:
         name: generated-image
         path: test.png


