name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - name: Installing package list
       run: apt list --installed
     - name: Install software
       run: |
         cd /home/runner/Downloads/
         curl -O https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip
         sudo unzip /home/runner/Downloads/chromedriver_linux64.zip -d /usr/local/bin
         chromedriver --version

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: run main
       env:
         MICRO_PASS: ${{ secrets.MICRO_PASS }}
       run: |
         python main.py
     - name: Upload image as artifact
       uses: actions/upload-artifact@v2
       with:
         name: generated-image
         path: test.png


